services:
  - type: web
    name: hvideo-lite-backend
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: sqlite+aiosqlite:///./hvideolite.db
      - key: PYTHON_VERSION
        value: 3.12.0
